appId: com.barrven.basic-pdf
productName: Basic PDF
directories:
  buildResources: build
files:
  - electron/**/*
  - src/**/*
  - index.html
  - icon.png
  - node_modules/**/*
  - package.json
fileAssociations:
  - ext: pdf
    name: PDF Document
    description: PDF Document
    mimeType: application/pdf
    role: Editor
win:
  target: nsis
  icon: icon.png
nsis:
  shortcutName: Basic PDF
  uninstallDisplayName: Basic PDF
mac:
  target: dmg
  icon: icon.png
linux:
  target: AppImage
  icon: icon.png
